"""
KRONOS Network Summary Page
Dedicated network analytics view consuming graph topology, centrality metrics, and community detection results.
"""

from typing import Optional
import streamlit as st
from utils.navigation import render_breadcrumb
from components.network_summary_view import render_network_summary_view
from components.empty_states import (
    render_backend_unavailable,
    render_empty_state,
    render_error_state
)
from services.network_service import network_service
from services.api_client import BackendUnavailableError, APIError


def render_network_summary_page() -> None:
    """Renders the network intelligence summary and topology console."""
    render_breadcrumb("Network Summary", "Graph Analytics")

    st.markdown(
        """
        <div style="margin-bottom: 1.25rem;">
            <h2 style="font-size: 1.25rem; font-weight: 700; color: #FFFFFF; margin: 0;">Network Topology & Graph Intelligence</h2>
            <p style="font-size: 0.8rem; color: #94A3B8; margin-top: 0.2rem;">
                Macro-level network structure, key node centrality rankings, and community clusters computed by Graph Analysis team.
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )

    active_case = st.session_state.get("selected_case_id")
    network_data = None
    backend_offline = False
    error_msg = None

    try:
        network_data = network_service.get_network_summary(case_id=active_case)
    except BackendUnavailableError as e:
        backend_offline = True
        error_msg = str(e)
    except Exception as e:
        error_msg = str(e)

    if backend_offline:
        render_backend_unavailable(error_msg)
    elif error_msg:
        render_error_state("Failed to Retrieve Graph Summary", error_msg)
    elif network_data:
        render_network_summary_view(network_data)
    else:
        render_empty_state(
            title="No Network Data Available",
            description="Graph analytics have not yet been generated by the Graph/Data Analysis team for this scope."
        )
