"""
KRONOS Suspicious Patterns Intelligence Page
Dedicated explorer for AI/NLP anomaly detections, burner phone rotations, and criminal network patterns.
"""

from typing import List
import streamlit as st
from utils.navigation import render_breadcrumb
from components.filters import render_pattern_filter_bar
from components.pattern_table import render_pattern_table
from components.empty_states import (
    render_backend_unavailable,
    render_empty_state,
    render_error_state
)
from services.pattern_service import pattern_service
from services.api_client import BackendUnavailableError, APIError


def render_suspicious_patterns_page() -> None:
    """Renders the AI/NLP suspicious pattern intelligence console."""
    render_breadcrumb("Suspicious Patterns", "Anomaly Feed")

    st.markdown(
        """
        <div style="margin-bottom: 1.25rem;">
            <h2 style="font-size: 1.25rem; font-weight: 700; color: #FFFFFF; margin: 0;">Suspicious Pattern Intelligence</h2>
            <p style="font-size: 0.8rem; color: #94A3B8; margin-top: 0.2rem;">
                Automated criminal anomaly detection stream generated by AI/NLP pipeline & graph behavioral analysis.
            </p>
        </div>
        """,
        unsafe_allow_html=True
    )

    # Filter Bar
    filter_data = render_pattern_filter_bar(key_prefix="patterns_page")

    active_case = st.session_state.get("selected_case_id")
    patterns = []
    backend_offline = False
    error_msg = None

    try:
        patterns = pattern_service.list_suspicious_patterns(
            severity=filter_data.get("severity"),
            min_confidence=filter_data.get("min_confidence"),
            case_id=active_case,
            query=filter_data.get("query")
        )
    except BackendUnavailableError as e:
        backend_offline = True
        error_msg = str(e)
    except Exception as e:
        error_msg = str(e)

    st.markdown('<div style="height: 1rem;"></div>', unsafe_allow_html=True)

    if backend_offline:
        render_backend_unavailable(error_msg)
    elif error_msg:
        render_error_state("Failed to Retrieve Patterns", error_msg)
    elif patterns:
        st.markdown(
            f"""
            <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 0.5rem;">
                <span style="font-size: 0.82rem; color: #94A3B8; font-weight: 600; text-transform: uppercase;">
                    Flagged Patterns ({len(patterns)} records)
                </span>
                {f'<span style="font-family: monospace; font-size: 0.72rem; color: #38BDF8;">Scope: {active_case}</span>' if active_case else ''}
            </div>
            """,
            unsafe_allow_html=True
        )
        render_pattern_table(patterns, key_prefix="patterns_page_feed")
    else:
        render_empty_state(
            title="No Suspicious Patterns Found",
            description="No suspicious patterns or behavioral anomalies match the current filter criteria."
        )
