"""
Network API Service for KRONOS
Consumes graph intelligence, centrality rankings, and community detection results
provided by the Graph/Data Analysis team via backend APIs.
"""

import logging
from typing import List, Optional, Dict, Any
from models.network import NetworkSummary, CentralEntity, CommunityCluster
from services.api_client import api_client, APIError, BackendUnavailableError

logger = logging.getLogger("kronos.network_service")


class NetworkService:
    """Service consuming Network & Graph Analytics APIs."""

    def __init__(self, client=api_client):
        self.client = client

    def get_network_summary(self, case_id: Optional[str] = None) -> NetworkSummary:
        """
        Fetch high-level network topology metrics generated by Graph team.
        """
        params = {}
        if case_id and case_id != "All":
            params["case_id"] = case_id

        endpoints = ["/network/summary", "/api/v1/network/summary", "/graph/summary"]
        
        last_error = None
        for endpoint in endpoints:
            try:
                data = self.client.get(endpoint, params=params)
                if isinstance(data, dict):
                    # Parse central entities if returned
                    raw_central = data.get("central_entities", data.get("key_entities", []))
                    central_entities = []
                    for c in raw_central:
                        central_entities.append(CentralEntity(
                            entity_id=str(c.get("entity_id", c.get("id", "UNKNOWN"))),
                            name=str(c.get("name", c.get("label", "Unknown"))),
                            type=str(c.get("type", "Person")),
                            degree=int(c.get("degree", c.get("degree_centrality", 0))),
                            betweenness_centrality=c.get("betweenness_centrality"),
                            degree_centrality=c.get("degree_centrality"),
                            pagerank=c.get("pagerank"),
                            community_id=c.get("community_id"),
                            risk_level=str(c.get("risk_level", "HIGH")).upper()
                        ))
                        
                    # Parse communities if returned
                    raw_comm = data.get("communities", data.get("clusters", []))
                    communities = []
                    for com in raw_comm:
                        communities.append(CommunityCluster(
                            community_id=int(com.get("community_id", com.get("id", 0))),
                            name=str(com.get("name", f"Cluster #{com.get('community_id', 0)}")),
                            member_count=int(com.get("member_count", com.get("size", 0))),
                            dominant_type=str(com.get("dominant_type", "Person")),
                            risk_level=str(com.get("risk_level", "MEDIUM")).upper(),
                            key_members=com.get("key_members", []),
                            description=com.get("description")
                        ))

                    return NetworkSummary(
                        total_nodes=int(data.get("total_nodes", data.get("nodes_count", 0))),
                        total_edges=int(data.get("total_edges", data.get("relationships_count", 0))),
                        network_density=data.get("network_density", data.get("density")),
                        communities_count=int(data.get("communities_count", len(communities))),
                        most_connected_entity=data.get("most_connected_entity"),
                        high_risk_clusters_count=int(data.get("high_risk_clusters_count", 0)),
                        central_entities=central_entities,
                        communities=communities,
                        relationship_types=data.get("relationship_types", {}),
                        temporal_activity=data.get("temporal_activity", {}),
                        metadata=data.get("metadata", {})
                    )
            except BackendUnavailableError:
                raise
            except Exception as e:
                last_error = e
                continue

        if last_error:
            raise last_error
        raise APIError("Failed to retrieve network summary from backend.")

    def get_central_entities(self, limit: int = 10, metric: str = "degree") -> List[CentralEntity]:
        """
        Fetch top ranked central entities from backend.
        """
        endpoints = ["/network/centrality", "/api/v1/network/centrality", "/graph/centrality"]
        params = {"limit": limit, "metric": metric}
        for endpoint in endpoints:
            try:
                data = self.client.get(endpoint, params=params)
                items = data if isinstance(data, list) else data.get("entities", [])
                results = []
                for c in items:
                    results.append(CentralEntity(
                        entity_id=str(c.get("entity_id", c.get("id", "UNKNOWN"))),
                        name=str(c.get("name", c.get("label", "Unknown"))),
                        type=str(c.get("type", "Person")),
                        degree=int(c.get("degree", 0)),
                        betweenness_centrality=c.get("betweenness_centrality"),
                        degree_centrality=c.get("degree_centrality"),
                        pagerank=c.get("pagerank"),
                        community_id=c.get("community_id"),
                        risk_level=str(c.get("risk_level", "HIGH")).upper()
                    ))
                return results
            except Exception:
                continue
        return []


network_service = NetworkService()
